before:
  hooks:
    - go mod download

env:
  - GO111MODULE=on

builds:
- &common
  goos:
    - darwin
    - windows
    - linux
  goarch:
    - amd64
  ldflags:
    - -s -w -X github.com/listx/grpc-tools/internal/versionflag.version={{.Version}}
  id: grpc-dump
  binary: grpc-dump
  main: ./grpc-dump
- <<: *common
  id: grpc-fixture
  binary: grpc-fixture
  main: ./grpc-fixture
- <<: *common
  id: grpc-replay
  binary: grpc-replay
  main: ./grpc-replay

brews:
-
  github:
    owner: listx
    name: homebrew-formulae
  homepage: "https://github.com/listx/grpc-tools"
  description: "A suite of gRPC debugging tools. Like Fiddler/Charles but for gRPC."

archives:
- replacements:
    darwin: macOS
    linux: Linux
    windows: Windows
  format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
